events {
    worker_connections 1024;  # Настройки для обработки соединений
}

http {
    upstream app {
        server app:8080;  # Имя контейнера из docker-compose.yml + порт
    }

    # Основной HTTP-сервер
    server {
        listen 80;  # Слушает порт 80 (HTTP)
        server_name fabrikahimchistki-nk.ru;  # Ваш домен (или localhost)

        location / {
            # Перенаправление всех запросов на бэкенд
            proxy_pass http://app;

            # Важные заголовки для корректной работы
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}